### ISSUE TITLE
trialIssueFromCollaborator

### ISSUE THREAD

**Issue by billyarky0218** [yvhime/collaborationTrial#1]
hi head dev. trying to post an issue if you can see this one. pls reply thanks.

-billyarky0218

**Comment by billyarky0218** [comment]
im also trying to drop a comment to see if it works

-billyarky0218

**Comment by billyarky0218** [comment]
@yvhime 

-billyarky0218

**Comment by yvhime** [comment]
@billyarky0218 saw your issue thanks

**Comment by billyarky0218** [comment]
@yvhime thanks head dev. will close this issue now

-yvhime

**Comment by billyarky0218** [comment]
but i can still comment? even if its closed?

-yvhime
